import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

import All from '../components/All'
import Flagged from '../components/Flagged'
import List from '../components/List'
import Scheduled from '../components/Scheduled'
import Today from '../components/Today'
import { RootState } from '../redux/store'
import { setList } from '../redux/listsSlice'
import { useDispatch, useSelector } from 'react-redux'
import SidePanel from '../components/SidePanel'

const Home: NextPage = () => {
  const [index, setIndex] = useState(0)
  const [listIndex, setListIndex] = useState(0)
  const dispatch = useDispatch()
  const lists = useSelector((state: RootState) => state.lists)

  const pages = [<Today />, <Scheduled />, <All />, <Flagged />]

  useEffect(() => {
    if (localStorage.lists !== undefined) {
      dispatch(setList(JSON.parse(localStorage.lists)))
    }
  }, [])

  return (
    <>
      <Head>
        <title>Reminders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SidePanel setListIndex={setListIndex} />
        <section className="right-view">
          {/* {pages[index]} */}
          <List {...lists.find(({ id }) => id == listIndex)!} />
        </section>
      </main>
    </>
  )
}

export default Home
