import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import List from '../components/List'
import { RootState } from '../redux/store'
import { useDispatch, useSelector } from 'react-redux'
import { setList } from '../redux/listsSlice'
import SidePanel from '../components/SidePanel'
import SmartList, { template } from '../components/SmartList'

const Home: NextPage = () => {
  const [listIndex, setListIndex] = useState(0)

  const dispatch = useDispatch()
  const lists = useSelector((state: RootState) => state.lists)

  useEffect(() => {
    if (localStorage.lists !== undefined) dispatch(setList(JSON.parse(localStorage.lists)))
  }, [])

  const setFavicon = () => {
    const color = lists.find(({ id }) => id == listIndex)
    return color ? color.color : template[listIndex].color
  }

  const setTitle = () => {
    const title = lists.find(({ id }) => id == listIndex)
    return title ? title.name : template[listIndex].name
  }

  return (
    <>
      <Head>
        <title>{setTitle()}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`/favicons/${setFavicon()}.png`} />
      </Head>

      <main>
        <SidePanel setListIndex={setListIndex} listIndex={listIndex} />
        <section className="right-view">
          {listIndex < 4 ? (
            <SmartList id={listIndex} />
          ) : (
            <List {...lists.find(({ id }) => id == listIndex)!} />
          )}
        </section>
      </main>
    </>
  )
}

export default Home
